### ISSUE TITLE
[MM-249] Todo 서버 변경사항 반영.

### ISSUE THREAD

**Issue by dydals3440** [M0IM/FE-M#171]
## 👀 어떤 기능을 추가할 것인가요?
> [MM-249] Todo 서버 변경사항 반영.

## 🍀 기능을 추가하기 위해 어떤 작업이 진행될 것인가요?
> 기능을 추가하는 과정에서 진행될 작업에 대해 간략히 설명해주세요!
- [x] planType ⇒ TODO_PLAN인 경우 planId 말고, todoId를 같이 받아 네비게이팅 연결.
- [x] planType 별 UI 분리
- [x] CalendarTodoDetailScreen UX 개선 
- [x] 문의하기, 이메일 API 연결

## ☕️ 어떤 브랜치에서 작업이 진행될까요?
> [MM-249]

## 📒 이해를 돕기 위한 참고 자료 및 스크린샷을 첨부해주세요. (선택사항)

[MM-246]: https://dydals3440.atlassian.net/browse/MM-246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MM-246]: https://dydals3440.atlassian.net/browse/MM-246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MM-249]: https://dydals3440.atlassian.net/browse/MM-249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MM-249]: https://dydals3440.atlassian.net/browse/MM-249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
